---
title: "Lab 10 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.

## Warm-up
1. Please load the homerange data `Tamburelloetal_HomeRangeDatabase.csv`

```{r}
library(tidyverse)
library(naniar)
library(janitor)
library(here)
```

```{r}
homerange <- read_csv(here("data", "Tamburelloetal_HomeRangeDatabase.csv")) %>% 
  clean_names()
```


2. Show the min, mean, and max log10.mass by taxonomic class in the dataset.

```{r}
summary_class_homerange <- 
  homerange %>% 
  group_by(class) %>% 
  summarise(
    min_log10_mass = min(log10_mass, na.rm = T),
    mean_log10_mass = mean(log10_mass, na.rm = T),
    max_log10_mass = max(log10_mass, na.rm = T)
  )
```


3. Make a plot that best summarizes this output.
```{r}
homerange %>% 
  ggplot(aes(x=class, y= log10_mass))+
  geom_boxplot()
```

